title: Wu Zhangchi
logo: /icon.jpg
description: Derick here! I graduated from the Chinese University of Hong Kong, Shenzhen, right now. And i am pursuing a ra/phd,u can contact me as soon as possible.
show_downloads: false
theme: jekyll-theme-minimal
