title: Derick
logo: /assets/img/1.jpg
description: Derick here! I graduated from the Chinese University of Hong Kong, Shenzhen, right now. And i am pursuing a ra/phd,feel free to contact me
show_downloads: false
theme: jekyll-theme-minimal
