title: Wu Zhangchi
logo: /assets/09cfe6b7d625c4ebe352b2eb6215c117.jpg
description: Derick here! I graduated from the Chinese University of Hong Kong, Shenzhen, right now. And i am pursuing a ra/phd,u can contact me as soon as possible.
show_downloads: false
theme: jekyll-theme-minimal
